name: newAdventurePlugin
version: 1.0.0
main: fr.loual.newadventure.NewAdventurePlugin
api-version: '1.21.6'
description: Plugin d'aventure global combinant Classes, Metiers et Mineraux (Cuprite).
author: Loual

commands:
  class:
    description: Commandes de gestion des classes
    usage: /class [choose|reset|get|set|info|help]
    aliases: [classes]
  job:
    description: Commandes de gestion des metiers et missions
    usage: /job [choose|reset|info|set]
    aliases: [jobs, metier, metiers]
  cuprite:
    description: Commande principale pour gerer la Cuprite
    usage: /cuprite [give|reload|help]
    aliases: [customminerals]
    permission: customminerals.admin
  nv:
    description: Activer ou desactiver la Vision Nocturne (Mineur / Architecte)
    usage: /nv
    aliases: [nightvision]
  craft:
    description: Ouvrir la table de craft a distance (Architecte M1)
    usage: /craft
    aliases: [workbench, wb]
  stonecutter:
    description: Ouvrir le tailleur de pierre a distance (Architecte M2)
    usage: /stonecutter
    aliases: [sc, nc]
  jb:
    description: Activer ou desactiver le Saut Ameliore II (Architecte M5)
    usage: /jb
    aliases: [jumpboost]
  casino:
    description: Commandes d'administration du Casino et du Blackjack
    usage: /casino [spawn|remove|help]
    aliases: [blackjack]
    permission: casino.admin
  croupier:
    description: Raccourci pour faire apparaitre un Croupier de Blackjack
    usage: /croupier
    permission: casino.admin
  sethome:
    description: Definir votre point de Home (Aventurier M1)
    usage: /sethome
    aliases: [set_home, sh]
  home:
    description: Se teleporter a votre point de Home (Aventurier M1)
    usage: /home
    aliases: [h]

permissions:
  customminerals.admin:
    description: Permet d'administrer les mineraux personnalises (Cuprite)
    default: op
  casino.admin:
    description: Permet de faire apparaitre ou supprimer des croupiers de casino
    default: op
